version: '3.1'
services:
    postgres:
        container_name: postgres-${API_NAME}
        image: postgres:latest
        restart: always
        expose:
            - ${POSTGRES_PORT}
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PGDATA: /data/postgres
        volumes:
            - ./docker/postgres/configs/postgres.conf:/etc/postgresql/postgresql.conf
            - ./docker/postgres/data:/var/lib/postgresql/data
            - ./docker/postgres/entrypoints/postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
        command: postgres -c config_file=/etc/postgresql/postgresql.conf -p ${POSTGRES_PORT}
        networks:
            - alternate

    mongodb:
        container_name: mongodb-${API_NAME}
        image: mongo:latest
        restart: always
        command: mongod --port ${MONGODB_PORT}
        ports:
            - ${MONGODB_PORT}:${MONGODB_PORT}
        environment:
            MONGO_INITDB_DATABASE: ${MONGODB_NAME}
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
        env_file:
            - .env
        volumes:
            - ./docker/mongodb/entrypoints/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
            - ./docker/mongodb/data:/data/db
        networks:
            - alternate

networks:
    alternate:
        driver: bridge
